"use client";

import {useCallback,useState} from "react";
import type {PartnerAllocationDetail} from "@/lib/ticketing/repository";

const statusLabel=(status:PartnerAllocationDetail["tickets"][number]["ticketStatus"])=>status==="ACTIVE"?"VALIDO":status==="USED"?"UTILIZZATO":status==="CANCELLED"?"ANNULLATO":"RIMBORSATO";

export default function StaffPartnerDetail({initialAllocation}:{initialAllocation:PartnerAllocationDetail}){
  const [allocation,setAllocation]=useState(initialAllocation);const [message,setMessage]=useState("");const [busy,setBusy]=useState("");
  const refresh=useCallback(async()=>{const response=await fetch(`/api/ticketing/staff/partner/${allocation.id}`,{cache:"no-store"});if(response.status===401){window.location.assign("/checkin");return;}if(response.ok){const body=await response.json() as {allocation:PartnerAllocationDetail};setAllocation(body.allocation);}},[allocation.id]);
  async function resend(){setBusy("resend");setMessage("");try{const response=await fetch(`/api/ticketing/staff/partner/${allocation.id}/resend`,{method:"POST"});if(response.status===401){window.location.assign("/checkin");return;}const body=await response.json() as {message?:string};if(!response.ok)throw new Error(body.message||"Reinvio non riuscito.");setMessage(body.message||"Inviti inviati nuovamente.");await refresh();}catch(error){setMessage(error instanceof Error?error.message:"Non è stato possibile reinviare gli inviti.");}finally{setBusy("");}}
  async function cancel(){if(!window.confirm("Annullare l'assegnazione e tutti i ticket ancora validi?"))return;setBusy("cancel");setMessage("");try{const response=await fetch(`/api/ticketing/staff/partner/${allocation.id}`,{method:"DELETE"});const body=await response.json() as {message?:string};if(!response.ok)throw new Error(body.message||"Annullamento non riuscito.");setMessage(body.message||"Assegnazione annullata.");await refresh();}catch(error){setMessage(error instanceof Error?error.message:"Non è stato possibile annullare l'assegnazione.");}finally{setBusy("");}}

  return <div className="staff-partner-detail"><section className="staff-partner-summary"><div><span>{allocation.status==="ACTIVE"?"ATTIVO":"ANNULLATO"}</span><h2>{allocation.companyName}</h2><p>{allocation.contactEmail||"Email referente non disponibile"}</p><p>{allocation.packageName||"Partnership"}</p></div><dl><div><dt>Biglietti assegnati</dt><dd>{allocation.allocatedQuantity}</dd></div><div><dt>Biglietti emessi</dt><dd>{allocation.ticketCount}</dd></div><div><dt>Utilizzati</dt><dd>{allocation.usedCount}</dd></div><div><dt>Ancora validi</dt><dd>{allocation.validCount}</dd></div></dl><div className="staff-partner-actions">{allocation.contactEmail&&<button type="button" onClick={resend} disabled={Boolean(busy)}>{busy==="resend"?"INVIO...":"REINVIA INVITI"}</button>}{allocation.status==="ACTIVE"&&allocation.usedCount===0&&<button type="button" className="is-danger" onClick={cancel} disabled={Boolean(busy)}>{busy==="cancel"?"ANNULLAMENTO...":"ANNULLA ASSEGNAZIONE"}</button>}</div></section>{message&&<p className="staff-feedback" role="status">{message}</p>}<section className="staff-partner-nominees"><h2>Ticket Partner</h2>{allocation.tickets.length===0?<p className="staff-empty">Nessun ticket emesso.</p>:allocation.tickets.map(ticket=><article key={ticket.ticketCode} className="staff-partner-ticket-row"><div><strong>Ingresso {ticket.sequenceNumber} di {ticket.totalQuantity}</strong><span>{ticket.ticketCode}</span></div><div><span className={`staff-ticket-state ${ticket.ticketStatus==="ACTIVE"?"is-valid":"is-used"}`}>{statusLabel(ticket.ticketStatus)}</span>{ticket.checkedInAt&&<time dateTime={ticket.checkedInAt}>Ingresso registrato</time>}</div><a href={`/api/ticketing/staff/partner/${allocation.id}/tickets/${encodeURIComponent(ticket.ticketCode)}`} target="_blank" rel="noopener noreferrer">APRI TICKET</a></article>)}</section></div>;
}
