"use client";

import {FormEvent,useCallback,useState} from "react";
import type {PartnerAllocationDetail} from "@/lib/ticketing/repository";

export default function StaffPartnerDetail({initialAllocation}:{initialAllocation:PartnerAllocationDetail}){
  const [allocation,setAllocation]=useState(initialAllocation);const [message,setMessage]=useState("");const [busy,setBusy]=useState("");
  const refresh=useCallback(async()=>{const response=await fetch(`/api/ticketing/staff/partner/${allocation.id}`,{cache:"no-store"});if(response.status===401){window.location.assign("/checkin");return;}if(response.ok){const body=await response.json() as {allocation:PartnerAllocationDetail};setAllocation(body.allocation);}},[allocation.id]);
  const payload=(form:HTMLFormElement)=>{const data=new FormData(form);return {firstName:data.get("firstName"),lastName:data.get("lastName"),email:data.get("email"),phone:data.get("phone")};};

  async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy("add");setMessage("");const form=event.currentTarget;try{const response=await fetch(`/api/ticketing/staff/partner/${allocation.id}/attendees`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload(form))});if(response.status===401){window.location.assign("/checkin");return;}const body=await response.json() as {message?:string};if(!response.ok)throw new Error(body.message||"Inserimento non riuscito.");form.reset();setMessage(body.message||"Nominativo aggiunto.");await refresh();}catch(error){setMessage(error instanceof Error?error.message:"Non è stato possibile aggiungere il nominativo.");}finally{setBusy("");}}
  async function update(event:FormEvent<HTMLFormElement>,attendeeId:string){event.preventDefault();setBusy(attendeeId);setMessage("");try{const response=await fetch(`/api/ticketing/staff/partner/${allocation.id}/attendees/${attendeeId}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload(event.currentTarget))});if(response.status===401){window.location.assign("/checkin");return;}const body=await response.json() as {message?:string};if(!response.ok)throw new Error(body.message||"Aggiornamento non riuscito.");setMessage(body.message||"Nominativo aggiornato.");await refresh();}catch(error){setMessage(error instanceof Error?error.message:"Non è stato possibile aggiornare il nominativo.");}finally{setBusy("");}}
  async function resend(ticketCode:string){setBusy(ticketCode);setMessage("");try{const response=await fetch("/api/ticketing/staff/resend-ticket",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ticketCode})});if(response.status===401){window.location.assign("/checkin");return;}const body=await response.json() as {message?:string};if(!response.ok)throw new Error(body.message||"Reinvio non riuscito.");setMessage(body.message||"Invito inviato nuovamente.");await refresh();}catch(error){setMessage(error instanceof Error?error.message:"Non è stato possibile reinviare l'invito.");}finally{setBusy("");}}
  async function cancel(){if(!window.confirm("Annullare l'assegnazione? I ticket già emessi resteranno validi e gli slot vuoti saranno liberati."))return;setBusy("cancel");setMessage("");try{const response=await fetch(`/api/ticketing/staff/partner/${allocation.id}`,{method:"DELETE"});const body=await response.json() as {message?:string};if(!response.ok)throw new Error(body.message||"Annullamento non riuscito.");setMessage(body.message||"Assegnazione annullata.");await refresh();}catch(error){setMessage(error instanceof Error?error.message:"Non è stato possibile annullare l'assegnazione.");}finally{setBusy("");}}

  return <div className="staff-partner-detail"><section className="staff-partner-summary"><div><span>{allocation.status==="ACTIVE"?"ATTIVO":"ANNULLATO"}</span><h2>{allocation.companyName}</h2><p>{allocation.packageName||"Partnership"}</p></div><dl><div><dt>Posti assegnati</dt><dd>{allocation.allocatedQuantity}</dd></div><div><dt>Nominativi</dt><dd>{allocation.ticketCount}</dd></div><div><dt>Da nominare</dt><dd>{allocation.unassignedCount}</dd></div></dl>{allocation.status==="ACTIVE"&&<button type="button" className="is-danger" onClick={cancel} disabled={busy==="cancel"}>{busy==="cancel"?"ANNULLAMENTO...":"ANNULLA ASSEGNAZIONE"}</button>}</section>{message&&<p className="staff-feedback" role="status">{message}</p>}{allocation.status==="ACTIVE"&&allocation.unassignedCount>0&&<section className="staff-partner-form"><h2>Aggiungi nominativo</h2><p>{allocation.unassignedCount} {allocation.unassignedCount===1?"slot disponibile":"slot disponibili"}</p><form onSubmit={add}><div><label><span>Nome *</span><input name="firstName" maxLength={80} required/></label><label><span>Cognome *</span><input name="lastName" maxLength={80} required/></label></div><div><label><span>Email *</span><input name="email" type="email" maxLength={160} required/></label><label><span>Telefono</span><input name="phone" type="tel" maxLength={40}/></label></div><button type="submit" disabled={busy==="add"}>{busy==="add"?"CREAZIONE...":"AGGIUNGI NOMINATIVO"}</button></form></section>}<section className="staff-partner-nominees"><h2>Nominativi e ticket</h2>{allocation.nominees.length===0?<p className="staff-empty">Nessun nominativo ancora inserito.</p>:allocation.nominees.map(nominee=><form key={nominee.attendeeId} onSubmit={event=>update(event,nominee.attendeeId)}><div className="staff-partner-nominee-head"><strong>{nominee.ticketCode}</strong><span>{nominee.emailSentAt?"EMAIL INVIATA":"EMAIL DA INVIARE"}</span></div><div><label><span>Nome</span><input name="firstName" defaultValue={nominee.firstName} maxLength={80} required/></label><label><span>Cognome</span><input name="lastName" defaultValue={nominee.lastName} maxLength={80} required/></label><label><span>Email</span><input name="email" type="email" defaultValue={nominee.email} maxLength={160} required/></label><label><span>Telefono</span><input name="phone" type="tel" defaultValue={nominee.phone??""} maxLength={40}/></label></div><footer><button type="submit" disabled={busy===nominee.attendeeId}>{busy===nominee.attendeeId?"SALVATAGGIO...":"MODIFICA NOMINATIVO"}</button><button type="button" className="is-secondary" onClick={()=>resend(nominee.ticketCode)} disabled={busy===nominee.ticketCode}>{busy===nominee.ticketCode?"INVIO...":"INVIA / REINVIA BIGLIETTO"}</button></footer></form>)}</section></div>;
}
