import PageHero from "@/components/PageHero";
import Icon from "@/components/Icon";
export default function Page(){return <>
<PageHero eyebrow="BE NIS BE NICE" title="Il programma associativo" accent="e di supporto NIS." intro="Unisciti a una rete di professionisti e persone attive nel mondo della salute che vogliono contribuire con competenze, network, progettualità e sostegno a costruire una sanità più equa, solidale e vicina alle persone." image="/images/hero-membership.jpg"/>
<section className="section soft"><div className="shell value-grid">
{[["Chi può aderire","people","Professionisti della salute e figure che operano o vogliono contribuire nel mondo della salute."],["Valore aggiunto","heart","Competenze, network, capacità progettuale, disponibilità operativa e sostegno."],["Ammissione","document","Le candidature sono valutate dai tre associati fondatori, con voto a maggioranza."],["Come candidarsi","mail","Compila il form, racconta esperienza, motivazione e valore aggiunto."]].map(x=><div className="value-card" key={x[0]}><div className="orb"><Icon name={x[1]}/></div><div><h3>{x[0]}</h3><p>{x[2]}</p></div></div>)}
</div></section>
<section className="section"><div className="shell form-panel"><form className="form-side dark"><div className="eyebrow white">DIVENTA PARTE DEL CAMBIAMENTO</div><h2 className="section-title">Invia la tua candidatura</h2><div className="form-grid"><label className="field">Nome e cognome *<input/></label><label className="field">Email *<input type="email"/></label><label className="field">Professione / Ruolo *<input/></label><label className="field">Motivazione *<input/></label><label className="field full">Quale valore aggiunto porteresti alla NIS?<textarea placeholder="Competenze, network, progettualità, supporto operativo o economico..."/></label></div><button type="button" className="btn btn-blue">INVIA LA CANDIDATURA ›</button></form><div className="form-side" style={{backgroundImage:"url('/images/hero-membership.jpg')",backgroundSize:"cover",backgroundPosition:"center"}}/></div></section>
</>}
