export type TicketEmailContentInput={firstName:string;lastName:string;ticketCode:string;category:string;amount:number|null;currency:string;qrToken:string;source?:"STANDARD"|"PARTNER";companyName?:string|null};

const publicSiteUrl="https://www.nazionaleitalianasanitari.com";
const escapeHtml=(value:string)=>value.replace(/[&<>"']/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[character]??character);
const formatPrice=(amount:number,currency:string)=>new Intl.NumberFormat("it-IT",{style:"currency",currency}).format(amount);

export function buildTicketUrl(qrToken:string){return `${publicSiteUrl}/biglietto/${encodeURIComponent(qrToken)}`;}

export function buildTicketEmailContent(input:TicketEmailContentInput){
  const partner=input.source==="PARTNER";const ticketUrl=buildTicketUrl(input.qrToken);const fullName=escapeHtml(`${input.firstName} ${input.lastName}`);const ticketCode=escapeHtml(input.ticketCode);const category=escapeHtml(partner?"INVITO PARTNER":input.category);const company=escapeHtml(input.companyName??"");const price=input.amount===null?null:escapeHtml(formatPrice(input.amount,input.currency));
  const companyRow=partner?`<tr><td style="padding:10px 0;border-top:1px solid #d9e3ec;color:#587087">Società</td><td style="padding:10px 0;border-top:1px solid #d9e3ec;text-align:right;font-weight:bold">${company}</td></tr>`:"";
  const priceRow=!partner&&price?`<tr><td style="padding:10px 0;border-block:1px solid #d9e3ec;color:#587087">Importo</td><td style="padding:10px 0;border-block:1px solid #d9e3ec;text-align:right;font-weight:bold">${price}</td></tr>`:"";
  const html=`<!doctype html><html lang="it"><body style="margin:0;background:#eef3f8;font-family:Arial,sans-serif;color:#15324e"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#eef3f8"><tr><td align="center" style="padding:30px 16px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:620px;background:#ffffff;border-top:6px solid #0b63b6"><tr><td style="padding:28px 34px;background:#061f3e;color:#ffffff"><img src="${publicSiteUrl}/logo/nis-logo-square.png" width="82" height="82" alt="Nazionale Italiana Sanitari" style="display:block;border-radius:6px;background:#fff"><h1 style="margin:20px 0 0;font-size:28px">NIS Gala Charity Night</h1></td></tr><tr><td style="padding:32px 34px"><h2 style="margin:0 0 12px;color:#073064;font-size:23px">${partner?"Il tuo invito partner è pronto.":"Il tuo ingresso è confermato."}</h2><p style="margin:0 0 24px;line-height:1.6">Ciao ${fullName}, ${partner?`la società ${company} ha riservato per te un invito nominativo.`:"il tuo biglietto personale è pronto."}</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse"><tr><td style="padding:10px 0;border-top:1px solid #d9e3ec;color:#587087">Codice ticket</td><td style="padding:10px 0;border-top:1px solid #d9e3ec;text-align:right;font-weight:bold">${ticketCode}</td></tr><tr><td style="padding:10px 0;border-top:1px solid #d9e3ec;color:#587087">Categoria</td><td style="padding:10px 0;border-top:1px solid #d9e3ec;text-align:right;font-weight:bold">${category}</td></tr>${companyRow}${priceRow}</table><p style="margin:28px 0;text-align:center"><a href="${ticketUrl}" style="display:inline-block;padding:15px 24px;background:#0b63b6;color:#ffffff;text-decoration:none;font-weight:bold;border-radius:4px">APRI IL TUO BIGLIETTO</a></p><p style="margin:0;color:#425d75;line-height:1.6">Mostra il QR Code presente nel biglietto all'ingresso.</p></td></tr></table></td></tr></table></body></html>`;
  const text=["NIS Gala Charity Night","",partner?"Il tuo invito partner è pronto.":"Il tuo ingresso è confermato.",`${input.firstName} ${input.lastName}`,`Codice ticket: ${input.ticketCode}`,`Categoria: ${partner?"INVITO PARTNER":input.category}`,...(partner?[`Società: ${input.companyName??""}`]:input.amount===null?[]:[`Importo: ${formatPrice(input.amount,input.currency)}`]),"",`Apri il tuo biglietto: ${ticketUrl}`,"Mostra il QR Code presente nel biglietto all'ingresso."].join("\n");
  return {subject:partner?"NIS Gala Charity Night - Il tuo invito partner":"NIS Gala Charity Night - Il tuo biglietto",html,text,ticketUrl};
}
