export type PartnerInvitationEmailInput={
  companyName:string;
  tickets:{ticketCode:string;qrToken:string;sequenceNumber:number;totalQuantity:number}[];
};

const publicSiteUrl="https://www.nazionaleitalianasanitari.com";
const escapeHtml=(value:string)=>value.replace(/[&<>"']/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[character]??character);
const ticketUrl=(qrToken:string)=>`${publicSiteUrl}/biglietto/${encodeURIComponent(qrToken)}`;

export function buildPartnerInvitationEmailContent(input:PartnerInvitationEmailInput){
  const company=escapeHtml(input.companyName);const total=input.tickets.length;
  const ticketRows=input.tickets.map(ticket=>`<tr><td style="padding:15px 0;border-top:1px solid #d9e3ec"><strong style="display:block;color:#073064">Ingresso ${ticket.sequenceNumber} di ${ticket.totalQuantity}</strong><span style="display:block;margin:4px 0 10px;color:#587087;font-size:13px">${escapeHtml(ticket.ticketCode)}</span><a href="${ticketUrl(ticket.qrToken)}" style="display:inline-block;padding:10px 16px;background:#0b63b6;color:#fff;text-decoration:none;font-weight:bold;border-radius:4px">APRI BIGLIETTO</a></td></tr>`).join("");
  const html=`<!doctype html><html lang="it"><body style="margin:0;background:#eef3f8;font-family:Arial,sans-serif;color:#15324e"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:30px 16px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:620px;background:#fff;border-top:5px solid #c8a967"><tr><td style="padding:28px 34px;background:#041d3b;color:#fff"><img src="${publicSiteUrl}/logo/nis-logo-square.png" width="82" height="82" alt="Nazionale Italiana Sanitari" style="display:block;border-radius:6px;background:#fff"><p style="margin:18px 0 5px;color:#d8c38e;font-size:12px;font-weight:bold">28 OTTOBRE 2026 · ROMA</p><h1 style="margin:0;font-size:28px">NIS Gala Charity Night</h1></td></tr><tr><td style="padding:30px 34px"><h2 style="margin:0 0 12px;color:#073064">I tuoi inviti Partner</h2><p style="margin:0 0 22px;line-height:1.6">La tua azienda <strong>${company}</strong> dispone di ${total} ingressi Partner per il NIS Gala Charity Night.</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f5f8fb"><tr><td style="padding:16px 18px"><strong style="display:block;color:#073064">Another Studio</strong><span>Via di Pietralata 183, Roma</span></td></tr><tr><td style="padding:16px 18px;border-top:1px solid #d9e3ec"><strong style="display:block;color:#073064">Parking Pietralata</strong><span>Via del Casale Rocchi 3, Roma</span></td></tr></table><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin-top:22px">${ticketRows}</table></td></tr><tr><td style="padding:16px 34px;background:#041d3b;color:#b8c7d7;font-size:12px;text-align:center">Nazionale Italiana Sanitari · Ticketing ufficiale NIS</td></tr></table></td></tr></table></body></html>`;
  const text=["NIS Gala Charity Night","28 ottobre 2026","",`La tua azienda ${input.companyName} dispone di ${total} ingressi Partner per il NIS Gala Charity Night.`,"","Another Studio - Via di Pietralata 183, Roma","Parking Pietralata - Via del Casale Rocchi 3, Roma","",...input.tickets.flatMap(ticket=>[`Ingresso ${ticket.sequenceNumber} di ${ticket.totalQuantity}`,ticket.ticketCode,ticketUrl(ticket.qrToken),""])].join("\n");
  return {subject:"NIS Gala Charity Night - I tuoi inviti Partner",html,text};
}
